/*
Group 10
Akshay Shukla 2022A7PS0087P
Gobind Singh 2022A7PS0083P
Siddhartha Gotur 2022A7PS0070P
Sriram Sudheer Hebbale 2022A7PS0147P
Granth Jain 2022A7PS0172P
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <time.h>

// Include the necessary headers for lexer and parser functions
#include "parserDef.h"
#include "lexerDef.h"

// Function prototype for measuring execution time of lexer and parser
void printTotalTime(char *inputFile, FILE* parseTreeOutFile);

int main(int argc, char** argv) {
    int choice;

    // Ensure correct command-line arguments are provided
    if (argc < 3) {
        printf("Usage: %s <input_file> <output_parse_tree_file>\n", argv[0]);
        return 1;
    }

    // Get file paths from command-line arguments
    char* filePath = argv[1];
    char* cleanFilePath = "cleaned_tc.txt"; // Temporary file for storing comment-free code

    // Infinite loop to handle menu-driven execution
    while (1) {
        // Display menu options
        printf("\nMenu:\n");
        printf("0: Exit\n");
        printf("1: Remove comments and print the comment-free code\n");
        printf("2: Print the token list generated by the lexer\n");
        printf("3: Parse and verify syntactic correctness, print errors and parse tree\n");
        printf("4: Print the total time taken by lexer and parser to verify syntactic correctness\n");
        printf("Enter your choice: ");
        
        // Get user input
        scanf("%d", &choice);

        // Token list pointer to store results from the lexer
        TokenList* tkns;

        // Process user's choice
        switch (choice) {
            case 0:
                // Exit the program
                printf("Exiting...\n");
                exit(0);

            case 1:
                // Remove comments from the source file and save the cleaned version
                removeComments(filePath, cleanFilePath);
                break;

            case 2:
                // Run the lexical analyzer and print tokens
                printf("\nRunning the lexical analyser. The output is as follows.\n");
                tkns = returnTokenList(filePath, choice);
                // printTokenList(tkns); // Uncomment this line if a print function is implemented
                break;

            case 3:
                // Run the lexical analyzer and print only lexical errors
                printf("\nRunning the lexical analyser. Printing only the errors generated by the lexical analyser\n");
                tkns = returnTokenList(filePath, choice);

                // Run the syntax analyzer and store the parse tree in the specified file
                printf("\nThe syntax analyser is running now. The output parse tree will be stored in the file %s\n", argv[2]);
                parseAndPrintErrors(tkns, argv[2]);
                printf("\nDone generating the parse tree\n");
                break;

            case 4:
                // Measure the execution time of lexer and parser
                printTotalTime(filePath, argv[2]);
                break;

            default:
                // Handle invalid input
                printf("\nInvalid choice. Please try again.\n");
        }
    }

    return 0;
}

// Function to measure and print the total time taken by the lexer and parser
// Input: inputFile - path to the source code file
//        parseTreeOutFile - path to the output parse tree file
// Output: Prints the total CPU time taken
void printTotalTime(char *inputFile, FILE* parseTreeOutFile) {
    clock_t start_time, end_time;
    double total_CPU_time, total_CPU_time_in_seconds;

    // Start measuring time
    start_time = clock();

    // Run the lexer and parser
    TokenList *tknlist = returnTokenList(inputFile, 4);
    parseAndPrintErrors(tknlist, parseTreeOutFile);

    // Stop measuring time
    end_time = clock();

    // Compute elapsed time in CPU cycles and convert to seconds
    total_CPU_time = (double)(end_time - start_time);
    total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;

    // Print the execution time
    printf("\nTotal CPU time in microseconds: %lf\n", total_CPU_time);
    printf("Total CPU time in seconds: %lf\n", total_CPU_time_in_seconds);
}
